disabled_rules:
  - trailing_whitespace

included:
  - Sources
  - Tests

line_length:
  warning: 200
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
  ignores_function_declarations: true